//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBOperations
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStories
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserStories()
        {
            this.Tasks = new HashSet<Tasks>();
        }
    
        public int UserStoryID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public int AssignedEmployeeID { get; set; }
        public System.DateTime DueDate { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public string Status { get; set; }
        public int StoryPoints { get; set; }
        public string Priority { get; set; }
    
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
